name: 'Manually Approve Workflow'
on:
  workflow_call:

permissions:
  issues: write

jobs:
  hold:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: trstringer/manual-approval@v1
        id: approval
        with:
          secret: ${{ github.token }}
          approvers: ${{ vars.APPROVERS }}
          timeout-minutes: 30
          issue-title: 'Production Deployment Approval'
          issue-body: 'Please approve the deployment to production.'